[package]
name = "wasm-demo"
version = "0.1.0"
authors = ["Thomas Lackemann <tommylackemann@gmail.com>"]

[dependencies]
stdweb = "*"
ttml = { git = "https://github.com/UnicornHeartClub/tabletop-macro-language" }
serde = "1.0.16"
serde_json = "1.0.4"
